name: TDP Cloud Builder

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: sh build.sh

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.1
          name: Release v0.1.1
          body: 优化会话管理
          draft: false
          prerelease: false
          files: |
            ./tdp-cloud/build/*
